name: Release Backup MX on Merge
on:
  push:
    branches: ["main"]
    paths:
      - "backup-mx/**"
jobs:
  build-images:
    uses: stefanabl/containers/.github/workflows/step-build.yaml@main
    secrets: inherit
    with:
      path: backup-mx
